# Generated by Django 4.2.9 on 2024-01-20 20:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0002_toolslistview"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ToolsListView",
            new_name="ToolsList",
        ),
    ]
